### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by fchapoton**
required change, as this file is loaded by some doctest inside sage !!

Please merge swiftly.

### CODE REVIEW

**Comment by fchapoton** [comment]
ping ?

**Comment by jasongrout** [comment]
Thanks for the ping!

**Comment by jasongrout** [comment]
> as this file is loaded by some doctest inside sage !!

Really? That seems odd. Is it pulled in from GitHub? Do you have a link to the test?

**Comment by fchapoton** [comment]
This is an optional internet doctest, located here. I think we need to change it. Could you make a new release with the python3 fixes ?
`
src/sage/repl/load.py:        sage: sage.repl.load.load('https://github.com/jasongrout/minimum_rank/raw/minimum_rank_1_0_0/minrank.py', globals())  # optional - internet
`

**Pull request merged**
